In [28]:
import numpy as np
grid = [[62,33,36,0,60,0,0,15,0,0],
       [0,0,0,76,37,0,0,84,0,0],
       [32,0,0,0,78,89,0,0,82,19],
       [0,58,0,90,93,0,0,0,13,0],
       [64,0,0,0,86,0,98,0,0,71],
       [0,4,67,0,0,96,0,0,41,0],
       [0,65,0,0,0,73,48,0,0,21],
       [0,54,0,0,0,100,0,44,0,0],
       [0,0,0,7,24,0,0,0,0,0],
       [53,0,25,28,51,8,0,46,0,10]]
print(np.matrix(grid))

"""
import numpy as np
grid = [[11,0,13,70,0,84,0,0,7,50],
       [0,0,0,89,0,0,0,0,0,47],
       [91,0,0,0,0,94,85,0,49,6],
       [0,0,0,0,0,0,0,0,52,43],
       [0,92,73,0,0,98,0,80,0,0],
       [16,75,0,97,78,81,100,67,0,0],
       [61,58,33,76,63,0,37,0,0,0],
       [0,0,0,55,36,0,64,41,26,23],
       [0,0,0,0,1,0,0,0,0,0],
       [0,0,0,0,20,29,2,0,22,27]]
print(np.matrix(grid))
"""

[[ 62  33  36   0  60   0   0  15   0   0]
 [  0   0   0  76  37   0   0  84   0   0]
 [ 32   0   0   0  78  89   0   0  82  19]
 [  0  58   0  90  93   0   0   0  13   0]
 [ 64   0   0   0  86   0  98   0   0  71]
 [  0   4  67   0   0  96   0   0  41   0]
 [  0  65   0   0   0  73  48   0   0  21]
 [  0  54   0   0   0 100   0  44   0   0]
 [  0   0   0   7  24   0   0   0   0   0]
 [ 53   0  25  28  51   8   0  46   0  10]]


'\nimport numpy as np\ngrid = [[11,0,13,70,0,84,0,0,7,50],\n       [0,0,0,89,0,0,0,0,0,47],\n       [91,0,0,0,0,94,85,0,49,6],\n       [0,0,0,0,0,0,0,0,52,43],\n       [0,92,73,0,0,98,0,80,0,0],\n       [16,75,0,97,78,81,100,67,0,0],\n       [61,58,33,76,63,0,37,0,0,0],\n       [0,0,0,55,36,0,64,41,26,23],\n       [0,0,0,0,1,0,0,0,0,0],\n       [0,0,0,0,20,29,2,0,22,27]]\nprint(np.matrix(grid))\n'

In [2]:
def missing():
    global grid
    m = []
    for n in range(1,101):
        add = True
        for i in range(10):
            if n in grid[i]:
                add = False
        if add == True:
            m.append(n)
    return m

In [3]:
missing()[:10]

[1, 2, 3, 5, 6, 9, 11, 12, 14, 16]

In [4]:
def find(n):
    global grid
    y = 11
    x = 11
    for i in range(10):
        for j in range(10):
            if grid[i][j] == n:
                y = i
                x = j
    if x == 11 and y == 11:
        return False
    else:
        return [y,x]

In [5]:
def find_closest_pos(n):
    c = 1
    while n+c in missing() and n + c <= 100:
        c += 1
    if n+c in missing() or n+c >100:
        return "NA"
    return n+c

In [6]:
def find_closest_neg(n):
    c = 1
    while n-c in missing() and n-c >= 1:
        c += 1
    if n-c in missing() or n-c == 0:
        return "NA"
    else:
        return n-c

In [7]:
def find_closest_index_pos(n):
    return find(find_closest_pos(n))

In [8]:
def find_closest_index_neg(n):
    return find(find_closest_neg(n))

In [9]:
def moves(n):
    global grid
    moves = []
    location = find(n)
    if location == False:
        return False
    else:
        y = location[0]
        x = location[1]
        try:
            if grid[y-2][x-1] == 0 and y-2 >= 0 and x-1 >= 0:
                moves.append([y-2,x-1])
        except: pass
        try:
            if grid[y-2][x+1] == 0 and y-2 >= 0 and x+1 >= 0:
                moves.append([y-2,x+1])
        except: pass
        try:
            if grid[y+2][x-1] == 0 and y+2 >= 0 and x-1 >= 0:
                moves.append([y+2,x-1])
        except: pass
        try:
            if grid[y+2][x+1] == 0 and y+2 >= 0 and x+1 >= 0:
                moves.append([y+2,x+1])
        except: pass
        try:
            if grid[y-1][x-2] == 0 and y-1 >= 0 and x-2 >= 0:
                moves.append([y-1,x-2])
        except: pass
        try:
            if grid[y+1][x-2] == 0 and y+1 >= 0 and x-2 >= 0:
                moves.append([y+1,x-2])
        except: pass
        try:
            if grid[y-1][x+2] == 0 and y-1 >= 0 and x+2 >= 0:
                moves.append([y-1,x+2])
        except: pass
        try:
            if grid[y+1][x+2] == 0 and y+1 >= 0 and x+2 >= 0:
                moves.append([y+1,x+2])
        except: pass
        
        return moves

In [10]:
moves(1)

False

In [11]:
def inter(a, b):
    i = []
    for l1 in a:
        for l2 in b:
            if l1 == l2:
                i.append(l1)
    return i

In [12]:
def distance(point1, point2):
    y1 = point1[0]
    x1 = point1[1]
    y2 = point2[0]
    x2 = point2[1]
    a = (y2-y1)**2
    b = (x2-x1)**2
    c = a + b
    return round(c**0.5,3)

In [13]:
distance([8,6],[5,1])

5.831

In [14]:
def empty():
    global grid
    options = []
    for i in range(10):
        for j in range(10):
            if grid[i][j] == 0:
                options.append([i,j])
    return options

In [15]:
def possible(n):
    global grid
    if n == 1:
        picks = []
        h = find_closest_pos(1)
        expected = (h-n)*2.3
        euclid = []
        options = empty()
        for m in options:
            euclid.append(distance(m,find_closest_index_pos(n)))
        for i in range(len(euclid)):
            if euclid[i] <= expected:
                picks.append(options[i])
        return picks
    else:
        final = []
        prev = []
        after = []
        if find_closest_neg(n) == n-1 and find_closest_pos(n) == n+1:
            prev = moves(n-1)
            after = moves(n+1)
            combined = inter(prev,after)
            return combined
        else:
            options = moves(n-1)
            c = False
            if find_closest_pos(n) != "NA":
                high = find_closest_pos(n)
                c = True
            if c == True:
                d = []
                required = round(len(options)/2)+1
                for m in options:
                    d.append(distance(m,find_closest_index_pos(n)))
                for i in range(required):
                    try:
                        index = d.index(min(d))
                    except: return final
                    final.append(options[index])
                    del d[index]
                    del options[index]
                return final
            else:
                return moves(n-1)

In [27]:
def solve():
    global grid
    for number in missing():
        for move in possible(number):
            row = move[0]
            col = move[1]
            grid[row][col] = number
            solve()
            grid[row][col] = 0
        return
    print(np.matrix(grid))
    input("\nHere is the next solution: *(Press enter)*")

In [29]:
solve()

[[ 62  33  36   1  60  77  38  15  18  83]
 [ 35   2  61  76  37  16  79  84  39  14]
 [ 32  63  34  59  78  89  92  17  82  19]
 [  3  58  75  90  93  80  85  88  13  40]
 [ 64  31  94  57  86  91  98  81  20  71]
 [ 55   4  67  74  99  96  87  72  41  12]
 [ 30  65  56  95  68  73  48  97  70  21]
 [  5  54  27  66  49 100  69  44  11  42]
 [ 26  29  52   7  24  47  50   9  22  45]
 [ 53   6  25  28  51   8  23  46  43  10]]


KeyboardInterrupt: ignored